services:
  aportes:
    image: ghcr.io/mau671/aportes:latest
    container_name: aportes-app
    environment:
      - UID=1000
      - GID=1000
      - TG_BOT_TOKEN=your_bot_token
      - TG_CHAT_ID=123456789
      - TMDB_API_TOKEN=your_tmdb_token
    volumes:
      - ./input:/app/input
      - ./config/rclone.conf:/app/rclone.conf
    command: ["-i", "/app/input", "--upload"]
