version: "3.9"

services:
  aportes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Miaubot
    environment:
      - UID=1000
      - GID=1000
      - TG_BOT_TOKEN=your_bot_token
      - TG_CHAT_ID=123456789
      - TMDB_API_TOKEN=your_tmdb_token
    volumes:
      - ./input:/app/input
      - ./config/rclone.conf:/app/rclone.conf
    command: >
      -i /app/input --upload --rc-config ./rclone.conf --rc-args="--fast-list" --rc-remote myRemote
